# -*- coding: utf-8 -*-
"""APICombustivelNOVO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GrEZ-iZt0Ve9UWVpZVR6yOWf_V1eHKoU
"""

import pandas as pd
import requests
import json
import seaborn as sns
import matplotlib.pyplot as plt

r = requests.get('link da api')
r.json()
r = json.loads(r.content)

r

"""# Jeito antigo, usando 
for"""

cont = 0
contm = 0
listaNomes = []
listaMedia = []
listaMenor = []
listaNomeMenor = []
listaMaior = []
listaNomeMaior = []
for i in range(0, 6):  
  x = (r['pesquisa_gerais']['items'][cont]['nome_produto'])
  y = (r['pesquisa_gerais']['items'][cont]['indices']['media'])
  z = (r['pesquisa_gerais']['items'][cont]['indices']['menor_preco'])
  z1 = (r['pesquisa_gerais']['items'][cont]['indices']['fornecedor_menor'])
  h = (r['pesquisa_gerais']['items'][cont]['indices']['maior_preco'])

  if ((r['pesquisa_gerais']['items'][cont]['indices']['maior_preco']) == (r['pesquisa_gerais']['items'][cont]['ranking'][contm]['preco'])):
    h1 = (r['pesquisa_gerais']['items'][cont]['ranking'][contm]['nome_fornecedor'])
    listaNomeMaior.append(h1)
  elif ((r['pesquisa_gerais']['items'][cont]['indices']['maior_preco']) == (r['pesquisa_gerais']['items'][cont]['ranking'][contm+1]['preco'])):
    h1 = (r['pesquisa_gerais']['items'][cont]['ranking'][contm+1]['nome_fornecedor'])
    listaNomeMaior.append(h1)
  elif ((r['pesquisa_gerais']['items'][cont]['indices']['maior_preco']) == (r['pesquisa_gerais']['items'][cont]['ranking'][contm-1]['preco'])):
    h1 = (r['pesquisa_gerais']['items'][cont]['ranking'][contm-1]['nome_fornecedor'])
    listaNomeMaior.append(h1)
    
  else:
    contm+=1
  
  
  cont +=1
  listaNomes.append(x)
  listaMedia.append(y)
  listaMenor.append(z)
  listaNomeMenor.append(z1)
  listaMaior.append(h)

  

print(listaNomes)
print(listaMedia)
print(listaMenor)
print(listaNomeMenor)
print(listaMaior)

d = {'Combustivel ' : listaNomes, 'Media preço': listaMedia, 'Menor preço': listaMenor, 'Nome fornecedor menor': listaNomeMenor, 'Maior preço': listaMaior, 'Nome fornecedor maior': listaNomeMaior}
df = pd.DataFrame(data=d)
df

from pylab import plot, show
#lista.sort()
plot(listaMedia)
show()

ind = []
elem = 0
for i in range(0, 6):
  ind.append(elem)
  elem += 1

from matplotlib import pyplot as plt
listaMedia.sort()
plt.bar(ind, listaMedia)

"""#OUTRO JEITO DE ANALISAR

"""

df =pd.json_normalize(r)
df

df.isnull().sum()

df.describe()

items = df["pesquisa_gerais.items"][0]
data_i = pd.json_normalize(items)
data_i.head()

plt.figure(figsize=(30,6))
df_dd = data_i[['indices.media', 'nome_produto']]
x1 = data_i['indices.media'].str.replace(',', '.').astype(float)
y1 = data_i['nome_produto']
sns.barplot(x1, y1)

plt.figure(figsize=(30,6))
df_dd = data_i[['indices.menor_preco', 'nome_produto']]
x1 = data_i['indices.menor_preco'].str.replace(',', '.').astype(float)
y1 = data_i['nome_produto']
sns.barplot(x1, y1)

plt.figure(figsize=(30,6))
df_dd = data_i[['indices.maior_preco', 'nome_produto']]
x1 = data_i['indices.maior_preco'].str.replace(',', '.').astype(float)
y1 = data_i['nome_produto']
sns.barplot(x1, y1)